env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-console:
    - error
    - allow:
      - info
      - warn
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
